Repository Cirle-7/social-media-app, pull requests merged in 2023-01, with the labels that each got.

#6 16-01-2023 = Setting Up MVC Structure
  app.js
  controllers/authController.js
  models/userModel.js
  package.json
  routes/userRoute.js
  server.js
  utils/appError.js
Labels: Main

#9 Added Errorhandler & Logger
  app.js
  controllers/errorController.js
  logs/all.log
  logs/error.log
  models/index.js
  models/userModel.js
  package-lock.json
  package.json
  utils/appError.js
  utils/logger.js
  utils/morgan.js
  validation/userValidation.js
Labels: Main

#15 Add user signup, login, authorize user functions
  app.js
  controllers/authController.js
  logs/all.log
  logs/error.log
  middleware/authentication.js
  models/index.js
  models/userModel.js
  package-lock.json
  package.json
  routes/userRoute.js
  utils/catchAsync.js
  validation/userValidation.js
Labels: Main, backend

#18 OAuth
  .gitignore
  app.js
  controllers/authController.js
  logs/all.log
  logs/error.log
  models/userModel.js
  package-lock.json
  package.json
  routes/userRoute.js
  server.js
  utils/passportOAuth.js
  views/profile.ejs
Labels: enhancement, backend, Auth
